# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Fecha'),
        ),
    ]
