# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180803_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biological',
            name='measure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biological', to='app.Measure', verbose_name='Medición'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='fumigation',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fumigation', to='app.Activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='measure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground', to='app.Measure', verbose_name='Medicion'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to='app.Activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='app.Activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='nutritional',
            name='measure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional', to='app.Measure', verbose_name='Medicion'),
        ),
        migrations.AlterField(
            model_name='prun',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prun', to='app.Activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
