# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180803_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('Fumigation', 'Fumigation'), ('Nutrition', 'Nutrition'), ('Prun', 'Prun'), ('Irrigation', 'Irrigation')], max_length=9, verbose_name='Tipo'),
        ),
    ]
