# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_activity_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('date', 'coordinates', 'crop')]),
        ),
    ]
