# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180803_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FumigationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Método')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='PrunMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Método')),
            ],
        ),
        migrations.AlterField(
            model_name='fumigation',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.FumigationType'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.IrrigationMethod'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.NutritionType'),
        ),
        migrations.AlterField(
            model_name='prun',
            name='method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.PrunMethod'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('date', 'coordinates', 'crop', 'type')]),
        ),
    ]
