# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180803_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='fumigation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.FumigationType'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.IrrigationMethod'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.NutritionType'),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha inicial'),
        ),
        migrations.AlterField(
            model_name='prun',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_in', to='app.PrunMethod'),
        ),
    ]
